### ISSUE TITLE
dpamber

### ISSUE THREAD

**Issue by RichardYjb** [njzjz/dpamber#5]
Hello, I got energy and force files (.mdout .mdfrc) with high precision. The low precision energy and force files (.mdout .mdfrc) were then obtained using the AmberDPRC and Reanalyze.mdin files. But, Using dpamber afterwards did not output the dataset file. Do I need to extract energy from the .mdout file and save it in the .mden file format? Or directly add -e .mden to the command in the process of running MD to let it generate the .mden file? The trajectory and energy in the manual do not seem to correspond.

**Comment by njzjz** [comment]
Could you provide an example?

**Comment by RichardYjb** [comment]
Thank you very much!













At 2022-11-11 13:13:35, "Jinzhe Zeng" ***@***.***> wrote:

Could you provide an example?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从网易163邮箱发来的超大附件推荐客户端极速下载
example.rar (60.91M, 2022年11月26日 17:25 到期)
下载

**Comment by njzjz** [comment]
@RichardYjb your link cannot be clicked on the GitHub.

**Comment by njzjz** [comment]
Two points:
(1) The files you sent me end with `.out` instead of `.mdout`.
(2) The script does not remove the energy for averages and RMS. I suggest using the `.mden` file.
