### ISSUE TITLE
why dpamber generate the datasets with box.npy, but still have the nopbc file?

### ISSUE THREAD

**Issue by Renws** [njzjz/dpamber#9]
In set.000 document, it have box.npy, but outside it, there is a nopbc file. The box information need to contain in the training process or not?

**Comment by njzjz** [comment]
The requirement of the box information is removed in https://github.com/deepmodeling/deepmd-kit/pull/810. Now it is kept for compatibility.

**Comment by Renws** [comment]
Is there anything else I need to do with the box information and the nopbc file before I start training the model？

**Comment by njzjz** [comment]
No.
